all:
	cd utility && make all
	cd eem && make all

install: all
	cd eem && make install

clean:
	cd utility && make clean
	cd eem && make clean

depend:
	cd utility && make depend
	cd eem && make depend
